services:
  backend:
    container_name: bb-backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data

  frontend:
    container_name: bb-frontend
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    container_name: bb-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
